
name: Build and Synth CDK Stack

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read  # This is required for actions/checkout
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v5
     
    # Use AWS Java to build
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'corretto'
        cache: maven
    
    - name: Install the latest AWS CDK
      run: |
        npm install -g aws-cdk
        echo "Node Version: $(node -v)"
        echo "CDK Version: $(cdk version)"
        
    - name: Build top level project which will have lambda jar ready for CDK build
      run: > 
        mvn install -DskipTests
        --no-transfer-progress --quiet
        
    - name: Synth CDK Stack
      working-directory: ./cdk
      env:
        ONLY_TAG_INFECTED: true
        VALIDATION_BUCKET: fake-validation-bucket
      run: > 
        cdk synth --require-approval=never --ci=true 
        --context bucketNames="fake-validation-bucket,fake-bucket-1,fake-bucket-2"
        --context addBucketPolicy="true"
      
